@startuml

autonumber
Title Betalings Sekvensdiagram
actor Bruger

boundary Kurv.jsp
boundary Kvitering.jsp

Bruger -> Kurv.jsp: start


box web
control FrontController
Kurv.jsp -> FrontController: doPost()
FrontController -> FrontController: processRequest()
FrontController -> Command: from()
Command --> FrontController: buyorder
FrontController -> BuyOrder: execute()
end box

box api
participant UserFacade
BuyOrder -> OrderFacade: getOrderById()
end box

box Database
OrderFacade -> DBOrder: getOrderByUserId()
participant DBUser
end box

database cupcake
DBOrder -> cupcake: executeQuery()
cupcake -> DBOrder: OK
DBOrder -> OrderFacade: OK
OrderFacade -> BuyOrder: OK

BuyOrder -> UserFacade: findUser()
UserFacade -> DBUser: findUser()
DBUser -> cupcake: executeQuery()
cupcake -> DBUser: OK
DBUser -> UserFacade: OK
UserFacade -> BuyOrder: OK

BuyOrder -> UserFacade: updateUserBank()
UserFacade -> DBUser: updateUserBank()
DBUser -> cupcake: executeUpdate()
cupcake -> DBUser: OK
DBUser -> UserFacade: OK
UserFacade -> BuyOrder: OK

BuyOrder -> OrderFacade: orderPurchased()
OrderFacade -> DBOrder: orderPurchased()
DBOrder -> cupcake: executeUpdate()
cupcake -> DBOrder: OK
DBOrder -> OrderFacade: OK
OrderFacade -> BuyOrder: OK

BuyOrder -> FrontController: Kvitering
FrontController -> Kvitering.jsp: forward()

@enduml